---
title: "**Celtic Sea Sprat  (Sprattus sprattus)**"
subtitle: "Supplementary Materials"
author: "L Kell"
date: "`r format(Sys.time(), '%d %B, %Y')`"
output: html_document
mathjax: TRUE
fig_width: 6 
fig_height: 4 
tags: FLR FLCore introduction
license: Creative Commons Attribution-ShareAlike 4.0 International Public License
bibliography: /home/laurie/Desktop/refs.bib
---

```{r, knitr, eval=TRUE, echo=FALSE, warning=FALSE, cache=FALSE}
knitr::opts_chunk$set(echo = FALSE)

library(knitr)

opts_chunk$set(cache     =TRUE, 
               comment   =NA, 
               warning   =FALSE, 
               message   =FALSE, 
               error     =FALSE, 
               echo      =FALSE, 
               eval      =TRUE,cache   =TRUE,
               cache.path="../cache/supmat/",
               fig.path  ="../figs/supMat/",
               fig.width =8,
               fig.height=6,
               dev       ="png")

iFig=0
iTab=0
```

```{r, dir}
setwd("/home/laurie/Desktop/inPrep/sprat")
dirOM  =file.path(getwd(),"data/om")
dirRes =file.path(getwd(),"data/results")
dirRuns=file.path(getwd(),"data/runs")
dirInp =file.path(getwd(),"data/inputs")
```

```{r, pkgs}
library(ggplot2); theme_set(theme_bw())

library(ggpubr)
library(ggcorrplot)
library(GGally)

library(plyr)
library(dplyr)
library(reshape)

library(FLCore)
library(FLBRP)
library(FLasher)
library(FLife)
library(ggplotFL)

library(FLCandy)
```


```{r, source}
h<-function(x) 1-exp(-x)
f<-function(x) -log(1-x)

sel<-function(x) catch.sel(x)%/%fapex(catch.sel(x))
```


```{r lh-fishlife, fig.height = 8, fig.width = 6}

```

**Figure `r iFig=iFig+1; iFig`** Life history parameters from *Fishlife*.






  
